---
namespace: nokia
name: nsp
version: 1.0.0
readme: README.md
authors:
  - Sven Wisotzky <sven.wisotzky@nokia.com>
description: Ansible collection for Nokia NSP
license:
  - BSD-3-Clause
tags:
  - nokia
  - nsp
  - networking
  - restconf
dependencies:
  ansible.netcommon: ">=5.2.0"
  ansible.utils: ">=3.0.0"
repository: https://github.com/nokia/nsp-ansible-integration
documentation: https://nokia.github.io/nsp-ansible-integration
homepage: https://nokia.github.io/nsp-ansible-integration
issues: https://github.com/nokia/nsp-ansible-integration/issues
build_ignore:
  - .github/
  - tools/
  - tests/
  - CHANGELOG.md
  - CONTRIBUTING.md
